# 生产环境配置

server:
  port: 8094

spring:
  application:
    name: zhiyan-ai-coze

  cloud:
    nacos:
      # Nacos服务发现配置
      discovery:
        username: nacos
        password: nacos
        server-addr: 10.7.10.98:8848  # Nacos服务地址
        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf  # Nacos命名空间ID
        group: DEFAULT_GROUP  # 业务服务的注册分组
        weight: 1

      # Nacos配置中心配置
      config:
        username: nacos
        password: nacos
        server-addr: 10.7.10.98:8848
        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf
        group: DEFAULT_GROUP  # 业务服务的配置分组
        file-extension: yaml

# Coze AI 配置 - 生产环境建议从环境变量读取敏感信息
coze:
  # API前缀地址
  api-url: https://api.coze.cn
  # Personal Access Token
  token: pat_ih9ougAlHVbc5JX56lbgrPKbTj1voME7yQ8HtnUAdSBfDi12qedJStHszsHi6LuO
  # 智能体ID
  bot-id: '7566182621098115087'
  # 智能体链接
  bot-url: https://www.coze.cn/s/KSEEgceeEXI/
  # 超时时间（毫秒）
  timeout: 60000
  # 最大 token 数量
  max-tokens: 4096
  # 是否启用流式传输
  stream-enabled: true
  # 连接超时时间（秒）
  connect-timeout: 30
  # 读取超时时间（秒）
  read-timeout: 60

# 日志配置
logging:
  level:
    root: INFO
    hbnu.project.zhiyanaicoze: INFO
    org.springframework.web.reactive: WARN
    org.springframework.cloud: WARN
    com.alibaba.nacos: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/zhiyan-ai-coze.log

