# 远程配置

server:
  port: 8094

## N8N 工作流配置
#n8n:
#  base-url: http://localhost:5678  # N8N 服务地址
#  api-key: ${N8N_API_KEY:your-api-key-here}  # API Key
#  timeout: 30000  # 请求超时时间（毫秒）
#
#  # 工作流配置
#  workflows:
#    # RAG 工作流
#    rag:
#      webhook-url: ${n8n.base-url}/webhook/rag-query
#      workflow-id: rag-workflow-001
#      enabled: true
#
#    # 文献检索工作流
#    literature-search:
#      webhook-url: ${n8n.base-url}/webhook/literature-search
#      workflow-id: literature-search-001
#      enabled: true

# 日志配置
logging:
  level:
    hbnu.project.zhiyanai: DEBUG
    org.springframework.web.reactive: DEBUG