# 生产环境配置

server:
  port: ${SERVER_PORT:8083}
  # 生产环境优化
  tomcat:
    max-threads: 500
    min-spare-threads: 50
    accept-count: 200
    max-connections: 10000

spring:
  # 数据源配置 - MySQL（生产环境）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:10.7.10.98}:${DB_PORT:3306}/${DB_NAME:zhiyan_knowledge_db}?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai&useSSL=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    # HikariCP连接池配置（生产环境优化）
    hikari:
      pool-name: WikiHikariPool-Prod
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境只验证，不自动修改表结构
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        generate_statistics: false
  
  # MongoDB配置（生产环境）
  data:
    mongodb:
      uri:
      auto-index-creation: false
  
  # Redis配置（如果需要）
  # redis:
  #   host: ${REDIS_HOST:redis-server}
  #   port: ${REDIS_PORT:6379}
  #   password: ${REDIS_PASSWORD}
  #   database: 0
  #   timeout: 10000
  #   ssl: true
  #   lettuce:
  #     pool:
  #       max-active: 20
  #       max-idle: 10
  #       min-idle: 5
  #       max-wait: 30000ms
  #     shutdown-timeout: 10000ms

# OSS配置（生产环境 - 阿里云OSS或其他云存储）
oss:
  type: minio # aliyun, minio, qiniu
  endpoint: http://10.7.10.98:9000
  access-key: root
  secret-key: rootroot
  bucket-name: wikiassets
  use-ssl: true
  domain: http://10.7.10.98:9000

# Feign客户端配置（生产环境）
feign:
  client:
    config:
      # 项目服务客户端
      zhiyan-project:
        url: ${PROJECT_SERVICE_URL:http://zhiyan-project:8095/project}
        connectTimeout: 10000
        readTimeout: 30000

# 日志配置 - 生产环境
logging:
  level:
    root: WARN
    com.alibaba.nacos: WARN
    hbnu.project.zhiyanwiki: INFO
    org.springframework.web: WARN
    org.springframework.cloud.openfeign: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.data.mongodb.core: INFO
  file:
    name: /var/log/zhiyan/zhiyan-wiki.log
  # 日志归档配置
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/zhiyan/archive/zhiyan-wiki-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 200MB
      max-history: 90
      total-size-cap: 50GB

# Actuator - 生产环境限制端点访问
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

