# 生产环境（服务器环境）

# zhiyan-knowledge
server:
  port: 8093

spring:
  application:
    name: zhiyan-knowledge

  cloud:
    nacos:
      # Nacos服务发现
      discovery:
        username: nacos  # 用户名
        password: nacos  # 密码
        # Nacos地址
        server-addr: 10.7.10.98:8848
        # 命名空间
        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf
        # 组
        group: DEFAULT_GROUP
        # 权重
        weight: 1

      # Nacos配置中心
      config:
        username: nacos  # 用户名
        password: nacos  # 密码
        # 和服务发现的一样
        server-addr: 10.7.10.98:8848
        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf
        group: DEFAULT_GROUP
        file-extension: yaml

    # OpenFeign配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true

  # 数据库配置
  datasource:
    url: jdbc:mysql://10.7.10.98:3306/zhiyan_knowledge_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: KnowledgeServiceHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # JPA配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

# JWT配置（需与认证服务保持一致）
jwt:
  secret: "zhiyan-platform-2025-this-is-a-very-long-secret-key-for-jwt-tokens-256-bits"
  issuer: "zhiyan-platform"

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    redis:
      enabled: false

# 日志配置
logging:
  level:
    # Nacos客户端日志级别
    com.alibaba.nacos: WARN
    # Spring Cloud相关日志级别
    org.springframework.cloud: INFO
    root: INFO
    hbnu.project.zhiyan: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: INFO
    # 关闭特定框架的冗余日志
    org.springframework.data.redis.repository: WARN
    # 关闭 Sentinel 控制台输出
    com.alibaba.csp.sentinel: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/zhiyan-knowledge-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Swagger配置
swagger:
  enabled: false
  title: "智研平台的知识管理模块"
  description: "学术成果、文献、专利管理"






