# 生产环境（服务器环境）

# zhiyan-knowledge 服务配置
server:
  port: 8093

spring:
  application:
    name: zhiyan-knowledge  # 服务名（业务标识，用于服务发现）

#  cloud:
#    nacos:
#      # Nacos服务发现配置
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: 10.7.10.98:8848  # Nacos服务地址
#        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf  # Nacos命名空间ID
#        group: DEFAULT_GROUP  # 业务服务的注册分组
#        weight: 1
#
#      # Nacos配置中心配置
#      config:
#        username: nacos
#        password: nacos
#        server-addr: 10.7.10.98:8848
#        namespace: 3936229d-c8b3-4947-9192-6b984dca44bf
#        group: DEFAULT_GROUP  # 业务服务的配置分组
#        file-extension: yaml

    # OpenFeign配置
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true

  # 数据库配置
  datasource:
    url: jdbc:mysql://10.7.10.98:3306/zhiyan_knowledge_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: KnowledgeServiceHikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000

  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # JPA配置
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false


# Seata 分布式事务配置
seata:
  enabled: false  # 生产环境启用Seata,先关了

  # 1. application-id：当前服务在Seata中的唯一标识
  # 作用：Seata用于区分不同的微服务实例，在事务日志和追踪中标识事务发起者/参与者
  # 建议：通常与spring.application.name保持一致（便于关联业务服务），也可自定义（需唯一）
  application-id: zhiyan-knowledge  # 此处修改为与服务名一致，更易维护

  # 2. tx-service-group：事务服务分组（核心配置）
  # 作用：用于将多个微服务划分到同一个事务组，Seata Server根据该分组路由事务协调请求
  # 配置规则：
  #   - 同一业务域的服务建议使用相同分组（如订单相关服务都用order-tx-group）
  #   - 命名格式推荐：[业务模块名]-tx-group（清晰区分业务）
  tx-service-group: zhiyan-knowledge-tx-group  # 知识模块专属事务组

  # 3. 注册中心配置（Seata客户端向注册中心注册，用于发现Seata Server）
  registry:
    type: nacos  # 注册中心类型（与服务发现一致，这里用Nacos）
    nacos:
      application: seata-server  # Seata Server在Nacos中的服务名（固定，与Seata Server配置一致）
      server-addr: 10.7.10.98:8848  # Nacos服务地址（与业务服务共用）
      namespace: 3936229d-c8b3-4947-9192-6b984dca44bf  # Nacos命名空间（与业务服务共用）
      group: SEATA_GROUP  # Seata专属注册分组（与业务服务的DEFAULT_GROUP隔离）
      username: nacos  # Nacos登录账号
      password: nacos  # Nacos登录密码

  # 4. 配置中心配置（Seata客户端从配置中心获取Seata Server的核心配置）
  config:
    type: nacos  # 配置中心类型（与业务配置一致，这里用Nacos）
    nacos:
      server-addr: 10.7.10.98:8848  # Nacos服务地址
      namespace: 3936229d-c8b3-4947-9192-6b984dca44bf  # Nacos命名空间
      group: SEATA_GROUP  # Seata专属配置分组（与业务配置的DEFAULT_GROUP隔离）
      data-id: seataServer.properties  # Seata Server的配置文件名（固定，与Seata Server配置一致）
      username: nacos
      password: nacos

  # 5. 服务映射配置（事务组与Seata Server集群的映射关系）
  service:
    vgroup-mapping:
      # 格式：[tx-service-group]: [Seata Server集群名]
      # 作用：指定当前事务组对应的Seata Server集群（需与Seata Server的集群名一致）
      # 这里"default"是Seata Server默认集群名，若Server配置了自定义集群名需同步修改
      zhiyan-knowledge-tx-group: default


# JWT配置
jwt:
  secret: "zhiyan-platform-2025-this-is-a-very-long-secret-key-for-jwt-tokens-256-bits"
  issuer: "zhiyan-platform"

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    redis:
      enabled: false

# 日志配置
logging:
  level:
    com.alibaba.nacos: WARN
    org.springframework.cloud: INFO
    root: INFO
    hbnu.project.zhiyan: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: INFO
    org.springframework.data.redis.repository: WARN
    com.alibaba.csp.sentinel: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/zhiyan-knowledge-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Swagger配置
swagger:
  enabled: false
  title: "智研平台的知识管理模块"
  description: "学术成果、文献、专利管理"