# Swagger 配置示例
swagger:
  # 是否启用 Swagger
  enabled: true
  # 标题
  title: 智研平台 API 文档
  # 描述
  description: 智研平台微服务系统 RESTful APIs
  # 版本
  version: 1.0.0
  # 服务条款 URL
  terms-of-service-url: ""
  # 联系人信息
  contact:
    name: 智研平台开发团队
    email: support@zhiyan.com
    url: https://github.com/ergou10086/ZhiyanPlatform
  # 许可证信息
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  # 是否启用认证
  auth-enabled: true
  # 认证 Header 名称
  auth-header-name: Authorization
  # 认证方案名称
  auth-scheme-name: Bearer Authentication
  # 认证描述
  auth-description: 请输入 JWT Token，格式：Bearer {token}

# SpringDoc OpenAPI 配置
springdoc:
  # API 文档路径
  api-docs:
    enabled: true
    path: /v3/api-docs
  # Swagger UI 配置
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    # 持久化认证信息
    persist-authorization: true
    # 显示请求时长
    display-request-duration: true
    # 操作排序：按方法排序
    operations-sorter: method
    # 标签排序：按字母排序
    tags-sorter: alpha
  # 默认 Consumes/Produces 媒体类型
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  # 包扫描路径
  packages-to-scan: hbnu.project
  # 路径匹配
  paths-to-match: /**

# Knife4j 增强配置
knife4j:
  # 启用增强功能
  enable: true
  # 是否显示默认的 Footer
  production: false
  # 基础认证
  basic:
    enable: false
  # Knife4j 设置
  setting:
    # 语言：中文
    language: zh_CN
    # 启用请求参数缓存
    enable-request-cache: true
    # 启用过滤多余的请求参数
    enable-filter-multipart-api-method-type: POST
    # 启用 Host
    enable-host: false
    # Host 地址
    enable-host-text: ""

